// Generated by typings
// Source: https://raw.githubusercontent.com/richard1122/vscode-youcompleteme/d44ddbc77f7b5af5ed906c28a6ea5f4a17970674/typings/ycm.d.ts
type YcmCompletionItem = {
    menu_text: string
    insertion_text: string
    detailed_info: string
    extra_menu_info: string
    kind: string
}

type YcmLocation = {
    filepath: string
    column_num: number
    line_num: number
}

type YcmRange = {
    start: YcmLocation
    end: YcmLocation
}

type YcmDiagnosticItem = {
    kind: 'ERROR' | 'WARNING'
    text: string
    ranges: YcmRange[]
    location: YcmLocation
    location_extent: YcmRange
    fixit_available: boolean
}

type YcmChunk = {
    range: YcmRange
    replacement_text: string
}

type YcmFixIt = {
    chunks: YcmChunk[]
    text: string
    location: YcmLocation
}

type YcmGetTypeResponse = {
    message: string
}